### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by justyna0bartoszewska** [khromov/polylang-woocommerce-multi-currency#3]
Could u please explain what i should do to swich this extension ?

**Comment by khromov** [comment]
You'll have to be more specific. What version of WooCommerce, Polylang? Have you read the README? Which part isn't working?

**Comment by justyna0bartoszewska** [comment]
Polylang  2.2.6 
WooCommerce 3.1.2
Hyyan WooCommerce Polylang Integration 1.0.3

Yes i read, but there is nothing about how swich on it. Please give some instructions.

**Comment by khromov** [comment]
@justyna0bartoszewska You set the currency for each language under the Language settings for Polylang, as per the screenshot in the README. If you have any other problems, feel free to post a new issue.
