### ISSUE TITLE
This plugin does nothing

### ISSUE THREAD

**Issue by simplenotezy** [khromov/polylang-woocommerce-multi-currency#6]
I have enabled the plugin but under my products I don't see an option to define multi currencies. Also documentation is really poor.

**Comment by khromov** [comment]
The currencies are defined by editing the Polylang Languages, not on the product level. You price translations according to their associated language currency.

**Comment by simplenotezy** [comment]
@khromov I see. However, we don't like to restrict currencies to a given language, but instead allow any language to display any currency that the user might want to use.

**Comment by khromov** [comment]
@simplenotezy Then I suggest you look into other options, like Aelia Currenty Switcher. In fact most other multi-currency solutions work in the way you describe.
