### ISSUE TITLE
WP < 6.7 and WooCommerce - compatibility problem, currency symbol missing

### ISSUE THREAD

**Issue by lukasprelovsky** [khromov/polylang-woocommerce-multi-currency#8]
Hi

i use Polylang for WooCommerce Multi-currency support

Ver 1.1 | Author: khromov

in last version woo and wp is missing currency symbol for main language.

if I have the turn on plugin

![currency (1)](https://github.com/user-attachments/assets/7ebf9cf9-927c-43e9-aea6-192de9bd46b5)

Polylang for WooCommerce Multi-currency

if I have the module turned off:

![currency (2)](https://github.com/user-attachments/assets/ab0be3b5-1386-4c98-b10a-695921b27669)

Kč - currency symbol in price

Thanks

**Comment by khromov** [comment]
I don't use this plugin any more and so can't fix the issue. But the plugin is very small, so you can probably fix it quite easily. Feel free to submit a PR if you do.
